sonar.projectKey=LightYagami28_TGbotPHP
sonar.organization=lightyagami28
sonar.projectName=TGbotPHP
sonar.projectVersion=3.0.0

sonar.sources=src,bin,examples
sonar.tests=tests
sonar.exclusions=vendor/**
sonar.sourceEncoding=UTF-8
