sonar.projectKey=LightYagami28_TGbotPHP
sonar.organization=lightyagami28

# Project metadata
sonar.projectName=TGbotPHP
sonar.projectVersion=2.0.0

# Source code path
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=vendor/**,tests/**

# Coverage
sonar.php.coverage.reportPaths=coverage/coverage.xml
